swagger: '2.0'
info:
  title: Module Risques
  description: >
    Le service d'interrogation du cadastre permet de faire le croisement entre un polygone ou un point et les données PPR(Plans de prévention des risques).
    L'api retourne des informations sur les risques par rapport à un polygone ou un point.
    Possibilité d'utiliser les communes de l'IGN ou les communes OSM


     ```json
        {"type":"FeatureCollection",
         "features":
          [{"type":"Feature",
           "geometry":
           {"type":"MultiPolygon","coordinates":[...]},
          "properties":{
            "idmap": xxx,
            "idgaspar": "xxx",
            "nom": "xxx",
            "etat": "xxx",
            "multi-risq": "xxx",
            "coderisque": "xxx",
            "nomrisque": "xxx",
            "site_web": "xxx",
            "uri_gaspar": "xxx"
          }
        ]}
       }

    ```




  version: '1.0'

schemes:
  - https
consumes:
  - application/json
basePath: /api
produces:
  - application/json
paths:
  /ppr/secteur:
    get:
      description: |
        Prends une variable de type departement contenant le numéro de département

        Paramètres de sorties : Retourne un résultat de Type "FeatureCollection" contenant toutes les informations PPR sur le département
      
      parameters:
        - name: numDepartement
          in: query
          description: Numéro département sur 2 ou 3 caractères(DOM)
          type: string
          required: false
      tags:
        - PPR Secteur
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/PPRs'

  /ppr/in:
    post:
      description: |
        Prends une geometrie de type GeoJSON en paramètre d'entrée geom

        Paramètres de sorties : Retourne un résultat de Type "FeatureCollection"
      tags: 
        - PPR In Geometrie
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/PPRs'
definitions:
  Geometry:
    type: object
    description: Une `Geometry` au sens GeoJSON
    externalDocs:
      url: http://geojson.org/geojson-spec.html#geometry-objects
      description: La documentation officielle du type `Geometry` de GeoJSON
    properties:
      type:
        type: string
        enum:
        - MultiPolygon
        - Point
        description: Le type corresponds au type de Géométrie(MultiPolygon ou Point)
      coordinates:
        type: array
        items:
          type: array
          items:
            type: number

  Feature:
    type: object
    description: Une `Feature` au sens GeoJSON
    externalDocs:
      url: http://geojson.org/geojson-spec.html#feature-objects
      description: La documentation officielle du type `Feature` de GeoJSON
    properties:
      type:
        type: string
        enum:
        - Feature
        description: La valeur de type est "Feature"
      id:
        type: string
      geometry:
        $ref: '#/definitions/Geometry'
      properties:
        type: object

  FeatureCollection:
    type: object
    description: Une `FeatureCollection` au sens GeoJSON
    externalDocs:
      url: http://geojson.org/geojson-spec.html#feature-collection-objects
      description: La documentation officielle du type `FeatureCollection` de GeoJSON
    properties:
      type:
        type: string
        enum:
        - FeatureCollection
        description: Le type est FeatureCollection
      features:
        type: array
        items:
          $ref: '#/definitions/Feature'

  PPR:
    description: ''
    allOf:
    - $ref: '#/definitions/Feature'
    - properties:
        properties:
          type: object
          properties:
            idmap:
              type: string
            idgaspar:
              type: string
            nom:
              type: string
              description: Information sur le type de PPR
            etat:
              type: string
            dateappro:
              type: dateTime
            datefinvall:
              type: dateTime
            multi-risq:
              type: string
            coderisque:
              type: string
            nomrisque:
              type: string
            site_web:
              type: string
            uri_gaspar:
              type: string

  PPRs:
    description: Une `FeatureCollection` contenant uniquement des features de type `PPR`
    allOf:
    - $ref: '#/definitions/FeatureCollection'
    - type: object
      properties:
        features:
          type: array
          items:
            $ref: '#/definitions/PPR'
